# Generated by Django 3.0.5 on 2022-09-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
