# Generated by Django 3.0.5 on 2022-09-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20220916_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('1', 'Programacion'), ('2', 'Calculo'), ('3', 'Bases de datos')], default='one', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
